[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_contract = "5w3tYtFnRHLH6VctigrowozRofysxdd5Zkc2bUN7sJZt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/arpit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
